{
    'name': 'Theme Common',
    'summary': 'Snippets Library',
    'description': 'Snippets library containing snippets to be styled in themes.',
    'category': 'Hidden',
    'version': '1.1',
    'depends': ['website'],
    'data': [
        'data/data.xml',
        'views/assets.xml',
        'views/theme_common_templates.xml',

        'views/old_snippets/s_animated_boxes.xml',
        'views/old_snippets/s_banner_parallax.xml',
        'views/old_snippets/s_big_icons.xml',
        'views/old_snippets/s_big_image.xml',
        'views/old_snippets/s_big_image_parallax.xml',
        'views/old_snippets/s_clonable_boxes.xml',
        'views/old_snippets/s_color_blocks_4.xml',
        'views/old_snippets/s_color_blocks_img.xml',
        'views/old_snippets/s_column.xml',
        'views/old_snippets/s_compact_menu.xml',
        'views/old_snippets/s_css_slider.xml',
        'views/old_snippets/s_discount.xml',
        'views/old_snippets/s_event_list.xml',
        'views/old_snippets/s_event_slide.xml',
        'views/old_snippets/s_features_carousel.xml',
        'views/old_snippets/s_full_menu.xml',
        'views/old_snippets/s_header_text_big_picture.xml',
        'views/old_snippets/s_icon_box.xml',
        'views/old_snippets/s_images_carousel.xml',
        'views/old_snippets/s_images_row.xml',
        'views/old_snippets/s_menu_three_columns.xml',
        'views/old_snippets/s_mini_nav_bar.xml',
        'views/old_snippets/s_news_carousel.xml',
        'views/old_snippets/s_page_header.xml',
        'views/old_snippets/s_pricing.xml',
        'views/old_snippets/s_products_carousel.xml',
        'views/old_snippets/s_profile.xml',
        'views/old_snippets/s_progress.xml',
        'views/old_snippets/s_separator_nav.xml',
        'views/old_snippets/s_showcase_image.xml',
        'views/old_snippets/s_showcase_slider.xml',
        'views/old_snippets/s_team_profiles.xml',
        'views/old_snippets/s_text_picture_text.xml',
        'views/old_snippets/s_three_columns_circle.xml',
        'views/old_snippets/s_two_columns.xml',
    ],
    'application': False,
}
