{
    'name': 'Theme Common',
    'summary': 'Snippets Library',
    'description': 'Snippets library containing snippets to be styled in Less Themes.',
    'category': 'Hidden',
    'version': '1.1',
    'author': 'Odoo SA',
    'depends': ['website'],
    'data': [
        # image placeholder
        'data/image_content.xml',
        # Assets
        'views/assets.xml',
        # CLEAN
        'views/s_big_image.xml',
        'views/s_big_image_parallax.xml',
        'views/s_color_blocks_2.xml',
        'views/s_color_blocks_4.xml',
        'views/s_column.xml',
        'views/s_discount.xml',
        'views/s_event_list.xml',
        'views/s_icon_box.xml',
        'views/s_icon_box_circle.xml',
        'views/s_icon_box_square.xml',
        'views/s_lead_bar.xml',
        'views/s_logo_bar.xml',
        'views/s_pricing.xml',
        'views/s_progress_bar.xml',
        'views/s_profile.xml',
        'views/s_separator_color.xml',
        'views/s_separator_shade.xml',
        'views/s_slide_banner.xml',
        'views/s_team_profiles.xml',
        'views/s_text_highlight.xml',
        'views/s_three_columns_circle.xml',
        'views/s_timeline.xml',
        'views/s_timeline_compact.xml',
        'views/s_two_columns.xml',
        # ENARK
        'views/s_testimonial_slider.xml',
        'views/s_big_icon_circle.xml',
        'views/s_big_icon_square.xml',
        # BEWISE
        'views/s_mini_nav_bar.xml',
        'views/s_separator_nav.xml',
        'views/s_separator_multicolor.xml',
        'views/s_separator_multicolor_fw.xml',
        'views/s_color_blocks_img.xml',
        'views/s_color_blocks_slider.xml',
        # ZAP
        'views/s_banner_2.xml',
        'views/s_carousel_boxed.xml',
        'views/s_features_circle.xml',
        'views/s_features_grid_circle.xml',
        'views/s_four_columns_fw.xml',
        'views/s_images_captions_fw.xml',
        'views/s_label.xml',
        'views/s_medias_list.xml',
        'views/s_news_carousel.xml',
        'views/s_numbers.xml',
        'views/s_page_header.xml',
        'views/s_process_steps_2.xml',
        'views/s_quotes_slider_2.xml',
        'views/s_references_2.xml',
        'views/s_tabs.xml',
        'views/s_team_profiles_2.xml',
        'views/s_three_columns_carousel.xml',
        'views/s_quote.xml',
        # KIDDO
        'views/s_1_column_text.xml',
        'views/s_2_column_text.xml',
        'views/s_3_column_text.xml',
        'views/s_4_column_text.xml',
        'views/s_banner_parallax.xml',
        'views/s_banner_3.xml',
        'views/s_big_picture_text.xml',
        'views/s_button_text.xml',
        'views/s_cubes.xml',
        'views/s_features_carousel.xml',
        'views/s_header_text_big_picture.xml',
        'views/s_product_list.xml',
        'views/s_separator_block.xml',
        'views/s_text_big_picture.xml',
        'views/s_text_picture_text.xml',
        'views/s_products_carousel.xml',
        # ANELUSIA
        'views/s_progress.xml',
        'views/s_menu_three_columns.xml',
        # GRAPHENE
        'views/s_media_block.xml',
        'views/s_animated_boxes.xml',
        'views/s_showcase.xml',
        'views/s_showcase_slider.xml',
        'views/s_masonry_block.xml',
        # AVANTGARDE
        'views/s_css_slider.xml',
        'views/s_showcase_image.xml',
        'views/s_clonable_boxes.xml',
        # TREEHOUSE
        'views/s_timeline_icons.xml',
        # MONGLIA
        'views/s_full_menu.xml',
        'views/s_compact_menu.xml',
        'views/s_event_slide.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'application': False,
}
