{
    'name': 'Theme Common',
    'summary': 'Snippets Library',
    'description': 'Snippets library containing snippets to be styled in themes.',
    'category': 'Hidden',
    'version': '1.1',
    'depends': ['website', 'website_theme_install'],
    'data': [
        'data/data.xml',
        'data/image_content.xml',
        'views/assets.xml',
        'views/theme_common_templates.xml',
        'views/s_google_map.xml',
        # CLEAN
        'views/s_big_image.xml',
        'views/s_big_image_parallax.xml',
        'views/s_color_blocks_2.xml',
        'views/s_color_blocks_4.xml',
        'views/s_column.xml',
        'views/s_discount.xml',
        'views/s_event_list.xml',
        'views/s_icon_box.xml',
        'views/s_pricing.xml',
        'views/s_progress_bar.xml',
        'views/s_profile.xml',
        'views/s_text_highlight.xml',
        'views/s_three_columns_circle.xml',
        'views/s_two_columns.xml',
        # ENARK
        'views/s_big_icons.xml',
        # BEWISE
        'views/s_mini_nav_bar.xml',
        'views/s_separator_nav.xml',
        'views/s_color_blocks_img.xml',
        # ZAP
        'views/s_badge.xml',
        'views/s_images_carousel.xml',
        'views/s_images_row.xml',
        'views/s_media_list.xml',
        'views/s_news_carousel.xml',
        'views/s_numbers.xml',
        'views/s_page_header.xml',
        'views/s_process_steps.xml',
        'views/s_team_profiles.xml',
        'views/s_blockquote.xml',
        'views/s_timeline.xml',
        # KIDDO
        'views/s_banner_parallax.xml',
        'views/s_features_carousel.xml',
        'views/s_header_text_big_picture.xml',
        'views/s_product_list.xml',
        'views/s_text_picture_text.xml',
        'views/s_products_carousel.xml',
        # ANELUSIA
        'views/s_progress.xml',
        'views/s_menu_three_columns.xml',
        # GRAPHENE
        'views/s_media_block.xml',
        'views/s_animated_boxes.xml',
        'views/s_showcase.xml',
        'views/s_showcase_slider.xml',
        'views/s_masonry_block.xml',
        # AVANTGARDE
        'views/s_css_slider.xml',
        'views/s_showcase_image.xml',
        'views/s_clonable_boxes.xml',
        # MONGLIA
        'views/s_full_menu.xml',
        'views/s_compact_menu.xml',
        'views/s_event_slide.xml',
    ],
    'application': False,
    'license': 'LGPL-3',
}
