{
    'name': 'Be Wise',
    'description': 'Be Wise Theme',
    'category': 'Theme/Education',
    'summary': 'Education, Schools, Young, Play, Kids, Sports',
    'sequence': 240,
    'version': '1.0',
    'depends': ['theme_common', 'website_animate'],
    'data': [
        'views/assets.xml',
        'views/image_content.xml',
        'views/customize_modal.xml',
        'views/snippets_options.xml',
        'views/snippets.xml',
        'views/image_library.xml',
    ],
    'images': [
        'static/description/bewise_description.jpg',
        'static/description/bewise_screenshot.jpeg',
    ],
    'price': 149,
    'currency': 'EUR',
    'live_test_url': 'https://theme-bewise.odoo.com/page/demo_page_demo_1',
    'license': 'LGPL-3',
}
